var aNavItemDate = [
	[
		{
			url:'',
			img:'imagesjrx/ph1.jpg',
			name:'小米MIX3',
			price:'3299元',
			tag:'新品'
		},
		{
			url:'',
			img:'imagesjrx/ph1.jpg',
			name:'小米MIX3',
			price:'3299元',
			tag:'新品'
		},
		{
			url:'',
			img:'imagesjrx/ph1.jpg',
			name:'小米MIX3',
			price:'3299元',
			tag:'新品'
		},
		{
			url:'',
			img:'imagesjrx/ph1.jpg',
			name:'小米MIX3',
			price:'3299元',
			tag:'新品'
		}
	],
	[
		{
			url:'',
			img:'imagesjrx/ph4.jpg',
			name:'小米MIX3',
			price:'3299元',
			tag:'热卖'
		},
		{
			url:'',
			img:'imagesjrx/ph2.jpg',
			name:'小米MIX3',
			price:'3299元',
			tag:'热卖'
		},
		{
			url:'',
			img:'imagesjrx/ph4.jpg',
			name:'小米MIX3',
			price:'3299元',
			tag:'热卖'
		},
		{
			url:'',
			img:'imagesjrx/ph2.jpg',
			name:'小米MIX3',
			price:'3299元',
			tag:'新品'
		}
	],
	[
		{
			url:'',
			img:'imagesjrx/el1.jpg',
			name:'小米MIX3',
			price:'3299元',
			tag:'热卖'
		},
		{
			url:'',
			img:'imagesjrx/el2.jpg',
			name:'小米MIX3',
			price:'3299元',
			tag:'热卖'
		},
		{
			url:'',
			img:'imagesjrx/el3.jpg',
			name:'小米MIX3',
			price:'3299元',
		},
		{
			url:'',
			img:'imagesjrx/el4.png',
			name:'小米MIX3',
			price:'3299元',
		},
		{
			url:'',
			img:'imagesjrx/el1.jpg',
			name:'小米MIX3',
			price:'3299元',
			tag:'热卖'
		},
		{
			url:'',
			img:'imagesjrx/el2.jpg',
			name:'小米MIX3',
			price:'3299元',
		}
	],
	[
		{
			url:'',
			img:'imagesjrx/bijiben.png',
			name:'小米笔记本',
			price:'4999元',
		},
		{
			url:'',
			img:'imagesjrx/bijiben.png',
			name:'小米笔记本',
			price:'4999元',
			tag:'热卖'
		},
		{
			url:'',
			img:'imagesjrx/bijiben.png',
			name:'小米笔记本',
			price:'4999元',
			tag:'热卖'
		},
		{
			url:'',
			img:'imagesjrx/bijiben.png',
			name:'小米笔记本',
			price:'4999元',
			tag:'新品'
		}
	],
	[
		{
			url:'',
			img:'imagesjrx/kongtiao.jpg',
			name:'米家互联网空调（一级能效）',
			price:'3299元',
			tag:'热卖'
		},
		{
			url:'',
			img:'imagesjrx/kongtiao.jpg',
			name:'米家互联网空调（一级能效）',
			price:'3299元',
			tag:'热卖'
		},
		{
			url:'',
			img:'imagesjrx/kongtiao.jpg',
			name:'米家互联网空调（一级能效）',
			price:'3299元',
		},
		{
			url:'',
			img:'imagesjrx/kongtiao.jpg',
			name:'米家互联网空调（一级能效）',
			price:'3299元',
			tag:'新品'
		}
	],
	[
		{
			url:'',
			img:'imagesjrx/ph3.jpg',
			name:'小米MIX3',
			price:'3299元',
			tag:'热卖'
		},
		{
			url:'',
			img:'imagesjrx/ph2.jpg',
			name:'小米MIX3',
			price:'3299元',
			tag:'热卖'
		},
		{
			url:'',
			img:'imagesjrx/ph2.jpg',
			name:'小米MIX3',
			price:'3299元',
			tag:'热卖'
		},
		{
			url:'',
			img:'imagesjrx/ph2.jpg',
			name:'小米MIX3',
			price:'3299元',
			tag:'新品'
		}
	],
	[
		{
			url:'',
			img:'imagesjrx/luyouqi.jpg',
			name:'小米路由器4',
			price:'199元',
			tag:'热卖'
		},
		{
			url:'',
			img:'imagesjrx/luyouqi.jpg',
			name:'小米路由器4',
			price:'199元',
			tag:'热卖'
		},
		{
			url:'',
			img:'imagesjrx/luyouqi.jpg',
			name:'小米路由器4',
			price:'199元',
			tag:'热卖'
		},
		{
			url:'',
			img:'imagesjrx/luyouqi.jpg',
			name:'小米路由器4',
			price:'199元',
			tag:'新品'
		}
	],
	[
		{
			url:'',
			img:'imagesjrx/ph3.jpg',
			name:'小米MIX3',
			price:'3299元',
			tag:'热卖'
		},
		{
			url:'',
			img:'imagesjrx/ph2.jpg',
			name:'小米MIX3',
			price:'3299元',
			tag:'热卖'
		},
		{
			url:'',
			img:'imagesjrx/ph2.jpg',
			name:'小米MIX3',
			price:'3299元',
			tag:'热卖'
		},
		{
			url:'',
			img:'imagesjrx/ph2.jpg',
			name:'小米MIX3',
			price:'3299元',
			tag:'新品'
		}
	],
	[
		{
			url:'',
			img:'imagesjrx/ph3.jpg',
			name:'小米MIX3',
			price:'3299元',
			tag:'热卖'
		},
		{
			url:'',
			img:'imagesjrx/ph2.jpg',
			name:'小米MIX3',
			price:'3299元',
			tag:'热卖'
		},
		{
			url:'',
			img:'imagesjrx/ph2.jpg',
			name:'小米MIX3',
			price:'3299元',
			tag:'热卖'
		},
		{
			url:'',
			img:'imagesjrx/ph2.jpg',
			name:'小米MIX3',
			price:'3299元',
			tag:'新品'
		}
	],
]

var aCateItemDate = [
	[
		{
			url:'',
			img:'imagesjrx/small1.jpg',
			name:'红米6X'
		},
		{
			url:'',
			img:'imagesjrx/small2.png',
			name:'小米8'
		},
		{
			url:'',
			img:'imagesjrx/small3.jpg',
			name:'米粉卡 日租卡'
		},
		{
			url:'',
			img:'imagesjrx/small1.jpg',
			name:'红米6X'
		},
		{
			url:'',
			img:'imagesjrx/small2.png',
			name:'小米8'
		},
		{
			url:'',
			img:'imagesjrx/small3.jpg',
			name:'米粉卡 日租卡'
		},
		{
			url:'',
			img:'imagesjrx/small1.jpg',
			name:'红米6X'
		},
		{
			url:'',
			img:'imagesjrx/small2.png',
			name:'小米8'
		},
		{
			url:'',
			img:'imagesjrx/small3.jpg',
			name:'米粉卡 日租卡'
		}
	],
	[
		{
			url:'',
			img:'imagesjrx/el1.jpg',
			name:'小米电视4A '
		},
		{
			url:'',
			img:'imagesjrx/el2.jpg',
			name:'小米电视4A 32英寸'
		},
		{
			url:'',
			img:'imagesjrx/el3.jpg',
			name:'小米电视4A 43英寸'
		},
		{
			url:'',
			img:'imagesjrx/el4.png',
			name:'小米电视4A 50英寸'
		},{
			url:'',
			img:'imagesjrx/el5.jpg',
			name:'小米电视4A 55英寸'
		},
		{
			url:'',
			img:'imagesjrx/el2.jpg',
			name:'小米电视4A 58英寸'
		}
	],
	[
		{
			url:'',
			img:'imagesjrx/bijiben.png',
			name:'小米笔记本'
		},
		{
			url:'',
			img:'imagesjrx/bijiben.png',
			name:'小米笔记本'
		},
		{
			url:'',
			img:'imagesjrx/bijiben.png',
			name:'小米笔记本'
		},
		{
			url:'',
			img:'imagesjrx/bijiben.png',
			name:'小米笔记本'
		},
		{
			url:'',
			img:'imagesjrx/bijiben.png',
			name:'小米笔记本'
		},
		{
			url:'',
			img:'imagesjrx/bijiben.png',
			name:'小米笔记本'
		}
	],
	[
		{
			url:'',
			img:'imagesjrx/kongtiao.jpg',
			name:'米家互联网空调'
		},
		{
			url:'',
			img:'imagesjrx/kongtiao.jpg',
			name:'米家互联网空调'
		},
		{
			url:'',
			img:'imagesjrx/kongtiao.jpg',
			name:'米家互联网空调'
		},
		{
			url:'',
			img:'imagesjrx/kongtiao.jpg',
			name:'米家互联网空调'
		}
	],
	[
		{
			url:'',
			img:'imagesjrx/pinghengche.jpg',
			name:'平衡车'
		},
		{
			url:'',
			img:'imagesjrx/pinghengche.jpg',
			name:'平衡车'
		},
		{
			url:'',
			img:'imagesjrx/pinghengche.jpg',
			name:'平衡车'
		},
		{
			url:'',
			img:'imagesjrx/pinghengche.jpg',
			name:'平衡车'
		},
		{
			url:'',
			img:'imagesjrx/pinghengche.jpg',
			name:'平衡车'
		},
		{
			url:'',
			img:'imagesjrx/pinghengche.jpg',
			name:'平衡车'
		},
		{
			url:'',
			img:'imagesjrx/pinghengche.jpg',
			name:'平衡车'
		},
		{
			url:'',
			img:'imagesjrx/pinghengche.jpg',
			name:'平衡车'
		}
	],
	[
		{
			url:'',
			img:'imagesjrx/luyouqi.jpg',
			name:'路由器'
		},
		{
			url:'',
			img:'imagesjrx/luyouqi.jpg',
			name:'路由器'
		},
		{
			url:'',
			img:'imagesjrx/luyouqi.jpg',
			name:'路由器'
		},
		{
			url:'',
			img:'imagesjrx/luyouqi.jpg',
			name:'路由器'
		},
		{
			url:'',
			img:'imagesjrx/luyouqi.jpg',
			name:'路由器'
		},
		{
			url:'',
			img:'imagesjrx/luyouqi.jpg',
			name:'路由器'
		},
		{
			url:'',
			img:'imagesjrx/luyouqi.jpg',
			name:'路由器'
		},
		{
			url:'',
			img:'imagesjrx/luyouqi.jpg',
			name:'路由器'
		},
		{
			url:'',
			img:'imagesjrx/luyouqi.jpg',
			name:'路由器'
		},
		{
			url:'',
			img:'imagesjrx/luyouqi.jpg',
			name:'路由器'
		}
	],
	[
		{
			url:'',
			img:'imagesjrx/yidongdianyuan.jpg',
			name:'移动电源'
		},
		{
			url:'',
			img:'imagesjrx/yidongdianyuan.jpg',
			name:'移动电源'
		},
		{
			url:'',
			img:'imagesjrx/yidongdianyuan.jpg',
			name:'移动电源'
		},
		{
			url:'',
			img:'imagesjrx/yidongdianyuan.jpg',
			name:'移动电源'
		},
		{
			url:'',
			img:'imagesjrx/yidongdianyuan.jpg',
			name:'移动电源'
		},
		{
			url:'',
			img:'imagesjrx/yidongdianyuan.jpg',
			name:'移动电源'
		},
		{
			url:'',
			img:'imagesjrx/yidongdianyuan.jpg',
			name:'移动电源'
		},
		{
			url:'',
			img:'imagesjrx/yidongdianyuan.jpg',
			name:'移动电源'
		},
		{
			url:'',
			img:'imagesjrx/yidongdianyuan.jpg',
			name:'移动电源'
		},
		{
			url:'',
			img:'imagesjrx/yidongdianyuan.jpg',
			name:'移动电源'
		}
	],
	[
		{
			url:'',
			img:'imagesjrx/chuifengji.jpg',
			name:'吹风机'
		},
		{
			url:'',
			img:'imagesjrx/chuifengji.jpg',
			name:'吹风机'
		},
		{
			url:'',
			img:'imagesjrx/chuifengji.jpg',
			name:'吹风机'
		},
		{
			url:'',
			img:'imagesjrx/chuifengji.jpg',
			name:'吹风机'
		},
		{
			url:'',
			img:'imagesjrx/chuifengji.jpg',
			name:'吹风机'
		},
		{
			url:'',
			img:'imagesjrx/chuifengji.jpg',
			name:'吹风机'
		},
		{
			url:'',
			img:'imagesjrx/chuifengji.jpg',
			name:'吹风机'
		},
		{
			url:'',
			img:'imagesjrx/chuifengji.jpg',
			name:'吹风机'
		}
	],
	[
		{
			url:'',
			img:'imagesjrx/erji.jpg',
			name:'耳机'
		},
		{
			url:'',
			img:'imagesjrx/erji.jpg',
			name:'耳机'
		},
		{
			url:'',
			img:'imagesjrx/erji.jpg',
			name:'耳机'
		},
		{
			url:'',
			img:'imagesjrx/erji.jpg',
			name:'耳机'
		},
		{
			url:'',
			img:'imagesjrx/erji.jpg',
			name:'耳机'
		},
		{
			url:'',
			img:'imagesjrx/erji.jpg',
			name:'耳机'
		},
		{
			url:'',
			img:'imagesjrx/erji.jpg',
			name:'耳机'
		},
		{
			url:'',
			img:'imagesjrx/erji.jpg',
			name:'耳机'
		}
	],
	[
		{
			url:'',
			img:'imagesjrx/quwenqi.jpg',
			name:'驱蚊器'
		},
		{
			url:'',
			img:'imagesjrx/quwenqi.jpg',
			name:'驱蚊器'
		},
		{
			url:'',
			img:'imagesjrx/quwenqi.jpg',
			name:'驱蚊器'
		},
		{
			url:'',
			img:'imagesjrx/quwenqi.jpg',
			name:'驱蚊器'
		},
		{
			url:'',
			img:'imagesjrx/quwenqi.jpg',
			name:'驱蚊器'
		},
		{
			url:'',
			img:'imagesjrx/quwenqi.jpg',
			name:'驱蚊器'
		},{
			url:'',
			img:'imagesjrx/quwenqi.jpg',
			name:'驱蚊器'
		},
		{
			url:'',
			img:'imagesjrx/quwenqi.jpg',
			name:'驱蚊器'
		}
	]
]

var aElecItemData = [
	[
		{
			url:'',
			img:'imagesjrx/el1.jpg',
			name:'小米MX2 8GB+128GB 黑',
			desc:'Unibody 全陶瓷',
			price:'3699',
			del:'4699',
			flag:{
				name:'off-flag',
				content:'减800元'
			},
			view:{
				recommend:'我要不催货，还不给我送货，都等了一个星期了，买了是为了看NBA',
				author:'yonghu'
			}
		},
		{
			url:'',
			img:'imagesjrx/el1.jpg',
			name:'小米MX2 8GB+128GB 黑',
			desc:'Unibody 全陶瓷',
			price:'3699',
			del:'4699',
			flag:{
				name:'new-flag',
				content:'新品'
			},
			view:{
				recommend:'我要不催货，还不给我送货，都等了一个星期了，买了是为了看NBA',
				author:'yonghu'
			}
		},
		{
			url:'',
			img:'imagesjrx/el1.jpg',
			name:'小米MX2 8GB+128GB 黑',
			desc:'Unibody 全陶瓷',
			price:'3699',
			del:'4699',
			flag:{
				name:'new-flag',
				content:'新品'
			},
			view:{
				recommend:'我要不催货，还不给我送货，都等了一个星期了，买了是为了看NBA',
				author:'yonghu'
			}
		},
		{
			url:'',
			img:'imagesjrx/el1.jpg',
			name:'小米MX2 8GB+128GB 黑',
			desc:'Unibody 全陶瓷',
			price:'3699',
			del:'4699',
			flag:{
				name:'new-flag',
				content:'新品'
			},
			view:{
				recommend:'我要不催货，还不给我送货，都等了一个星期了，买了是为了看NBA',
				author:'yonghu'
			}
		},
		{
			url:'',
			img:'imagesjrx/el1.jpg',
			name:'小米MX2 8GB+128GB 黑',
			desc:'Unibody 全陶瓷',
			price:'3699',
			del:'4699',
			flag:{
				name:'off-flag',
				content:'减800元'
			},
			view:{
				recommend:'我要不催货，还不给我送货，都等了一个星期了，买了是为了看NBA',
				author:'yonghu'
			}
		},
		{
			url:'',
			img:'imagesjrx/el1.jpg',
			name:'小米MX2 8GB+128GB 黑',
			desc:'Unibody 全陶瓷',
			price:'3699',
			del:'4699',
			flag:{
				name:'off-flag',
				content:'减800元'
			},
			view:{
				recommend:'我要不催货，还不给我送货，都等了一个星期了，买了是为了看NBA',
				author:'yonghu'
			}
		},
		{
			url:'',
			img:'imagesjrx/el1.jpg',
			name:'小米MX2 8GB+128GB 黑',
			desc:'Unibody 全陶瓷',
			price:'3699',
			del:'4699',
			flag:{
				name:'off-flag',
				content:'减800元'
			},
			view:{
				recommend:'我要不催货，还不给我送货，都等了一个星期了，买了是为了看NBA',
				author:'yonghu'
			}
		},
		{
			top:{
				url:'',
				img:'imagesjrx/hezi.jpg',
				name:'小米盒子',
				price:'199'
			},
			bottom:{
				url:'',
				txt:'浏览更多',
				tag:'热门',
				icon:'&#xe615;'
			}
		}
	],
	[
		{
			url:'',
			img:'imagesjrx/el2.jpg',
			name:'小米电视',
			desc:'Unibody 全陶瓷',
			price:'3699',
			del:'4699',
			view:{
				recommend:'我要不催货，还不给我送货，都等了一个星期了，买了是为了看NBA',
				author:'yonghu'
			}
		},
		{
			url:'',
			img:'imagesjrx/el2.jpg',
			name:'小米电视',
			desc:'Unibody 全陶瓷',
			price:'3699',
			del:'4699',
			view:{
				recommend:'我要不催货，还不给我送货，都等了一个星期了，买了是为了看NBA',
				author:'yonghu'
			}
		},
		{
			url:'',
			img:'imagesjrx/el2.jpg',
			name:'小米电视',
			desc:'Unibody 全陶瓷',
			price:'3699',
			del:'4699',
			view:{
				recommend:'我要不催货，还不给我送货，都等了一个星期了，买了是为了看NBA',
				author:'yonghu'
			}
		},
		{
			url:'',
			img:'imagesjrx/el2.jpg',
			name:'小米电视',
			desc:'Unibody 全陶瓷',
			price:'3699',
			del:'4699',
			flag:{
				name:'new-flag',
				content:'新品'
			},
			view:{
				recommend:'我要不催货，还不给我送货，都等了一个星期了，买了是为了看NBA',
				author:'yonghu'
			}
		},
		{
			url:'',
			img:'imagesjrx/el3.jpg',
			name:'小米电视',
			desc:'Unibody 全陶瓷',
			price:'3699',
			del:'4699',
			flag:{
				name:'off-flag',
				content:'减800元'
			},
			view:{
				recommend:'我要不催货，还不给我送货，都等了一个星期了，买了是为了看NBA',
				author:'yonghu'
			}
		},
		{
			url:'',
			img:'imagesjrx/el3.jpg',
			name:'小米电视',
			desc:'Unibody 全陶瓷',
			price:'3699',
			del:'4699',
			flag:{
				name:'off-flag',
				content:'减800元'
			},
			view:{
				recommend:'我要不催货，还不给我送货，都等了一个星期了，买了是为了看NBA',
				author:'yonghu'
			}
		},
		{
			url:'',
			img:'imagesjrx/el3.jpg',
			name:'小米电视',
			desc:'Unibody 全陶瓷',
			price:'3699',
			del:'4699',
			flag:{
				name:'new-flag',
				content:'新品'
			},
			view:{
				recommend:'我要不催货，还不给我送货，都等了一个星期了，买了是为了看NBA',
				author:'yonghu'
			}
		},
		{
			top:{
				url:'',
				img:'imagesjrx/ca.png',
				name:'小米MX2 8GB+128GB 黑',
				price:'3699',
			},
			bottom:{
				url:'',
				txt:'浏览更多',
				tag:'热门',
				icon:'&#xe615;'
			}
		}
	],
	[
		{
			url:'',
			img:'imagesjrx/bijiben.png',
			name:'小米电脑',
			desc:'Unibody 全陶瓷',
			price:'3699',
			del:'4699',
			flag:{
				name:'off-flag',
				content:'减800元'
			},
			view:{
				recommend:'我要不催货，还不给我送货，都等了一个星期了，买了是为了看NBA',
				author:'yonghu'
			}
		},
		{
			url:'',
			img:'imagesjrx/bijiben.png',
			name:'小米电脑',
			desc:'Unibody 全陶瓷',
			price:'3699',
			del:'4699',
			flag:{
				name:'off-flag',
				content:'减800元'
			},
			view:{
				recommend:'我要不催货，还不给我送货，都等了一个星期了，买了是为了看NBA',
				author:'yonghu'
			}
		},
		{
			url:'',
			img:'imagesjrx/bijiben.png',
			name:'小米电脑',
			desc:'Unibody 全陶瓷',
			price:'3699',
			del:'4699',
			flag:{
				name:'off-flag',
				content:'减800元'
			},
			view:{
				recommend:'我要不催货，还不给我送货，都等了一个星期了，买了是为了看NBA',
				author:'yonghu'
			}
		},
		{
			url:'',
			img:'imagesjrx/bijiben.png',
			name:'小米电脑',
			desc:'Unibody 全陶瓷',
			price:'3699',
			del:'4699',
			view:{
				recommend:'我要不催货，还不给我送货，都等了一个星期了，买了是为了看NBA',
				author:'yonghu'
			}
		},
		{
			url:'',
			img:'imagesjrx/bijiben.png',
			name:'小米电脑',
			desc:'Unibody 全陶瓷',
			price:'3699',
			del:'4699',
			view:{
				recommend:'我要不催货，还不给我送货，都等了一个星期了，买了是为了看NBA',
				author:'yonghu'
			}
		},
		{
			url:'',
			img:'imagesjrx/bijiben.png',
			name:'小米电脑',
			desc:'Unibody 全陶瓷',
			price:'3699',
			del:'4699',
			flag:{
				name:'off-flag',
				content:'减800元'
			},
			view:{
				recommend:'我要不催货，还不给我送货，都等了一个星期了，买了是为了看NBA',
				author:'yonghu'
			}
		},
		{
			url:'',
			img:'imagesjrx/bijiben.png',
			name:'小米电脑',
			desc:'Unibody 全陶瓷',
			price:'3699',
			del:'4699',
			flag:{
				name:'new-flag',
				content:'新品'
			},
			view:{
				recommend:'我要不催货，还不给我送货，都等了一个星期了，买了是为了看NBA',
				author:'yonghu'
			}
		},
		{
			top:{
				url:'',
				img:'imagesjrx/ca.png',
				name:'小米MX2 8GB+128GB 黑',
				price:'3699',
			},
			bottom:{
				url:'',
				txt:'浏览更多',
				tag:'热门',
				icon:'&#xe615;'
			}
		}
	],
	[
		{
			url:'',
			img:'imagesjrx/jiqiren.jpg',
			name:'小米扫地机器人',
			desc:'Unibody 全陶瓷',
			price:'3699',
			del:'4699',
			view:{
				recommend:'我要不催货，还不给我送货，都等了一个星期了，买了是为了看NBA',
				author:'yonghu'
			}
		},
		{
			url:'',
			img:'imagesjrx/jiqiren.jpg',
			name:'小米扫地机器人',
			desc:'Unibody 全陶瓷',
			price:'3699',
			del:'4699',
			view:{
				recommend:'我要不催货，还不给我送货，都等了一个星期了，买了是为了看NBA',
				author:'yonghu'
			}
		},
		{
			url:'',
			img:'imagesjrx/jiqiren.jpg',
			name:'小米扫地机器人',
			desc:'Unibody 全陶瓷',
			price:'3699',
			del:'4699',
			flag:{
				name:'new-flag',
				content:'新品'
			},
			view:{
				recommend:'我要不催货，还不给我送货，都等了一个星期了，买了是为了看NBA',
				author:'yonghu'
			}
		},
		{
			url:'',
			img:'imagesjrx/jiqiren.jpg',
			name:'小米扫地机器人',
			desc:'Unibody 全陶瓷',
			price:'3699',
			del:'4699',
			flag:{
				name:'off-flag',
				content:'减800元'
			},
			view:{
				recommend:'我要不催货，还不给我送货，都等了一个星期了，买了是为了看NBA',
				author:'yonghu'
			}
		},
		{
			url:'',
			img:'imagesjrx/shoudiantong.jpg',
			name:'小米随身手电筒',
			desc:'Unibody 全陶瓷',
			price:'3699',
			del:'4699',
			flag:{
				name:'new-flag',
				content:'新品'
			},
			view:{
				recommend:'我要不催货，还不给我送货，都等了一个星期了，买了是为了看NBA',
				author:'yonghu'
			}
		},
		{
			url:'',
			img:'imagesjrx/shoudiantong.jpg',
			name:'小米随身手电筒',
			desc:'Unibody 全陶瓷',
			price:'3699',
			del:'4699',
			view:{
				recommend:'我要不催货，还不给我送货，都等了一个星期了，买了是为了看NBA',
				author:'yonghu'
			}
		},
		{
			url:'',
			img:'imagesjrx/shoudiantong.jpg',
			name:'小米随身手电筒',
			desc:'Unibody 全陶瓷',
			price:'3699',
			del:'4699',
			view:{
				recommend:'我要不催货，还不给我送货，都等了一个星期了，买了是为了看NBA',
				author:'yonghu'
			}
		},
		{
			top:{
				url:'',
				img:'imagesjrx/ca.png',
				name:'小米MX2 8GB+128GB 黑',
				price:'3699',
			},
			bottom:{
				url:'',
				txt:'浏览更多',
				tag:'热门',
				icon:'&#xe615;'
			}
		}
	]
]

