var _util = require('util')

var _cart = {
	//添加购物车
	addCart:function(data,success,error){
		_util.request({
			url:'/cart',
			method:'post',
			data:data,
			success:success,
			error:error			
		})		
	},
	//前台获取购物车信息
	getCartCount:function(success,error){
		_util.request({
			url:'/cart/count',
			success:success,
			error:error
		})
	},
	//后台获取购物车信息
	getCart:function(success,error){
		_util.request({
			url:'/cart',
			success:success,
			error:error
		})
	},
	//购物车选中(单选)
	selectOne:function(data,success,error){
		_util.request({
			url:'/cart/selectOne',
			method:'put',
			data:data,
			success:success,
			error:error			
		})		
	},
	//购物车不选(单选)
	unselectOne:function(data,success,error){
		_util.request({
			url:'/cart/unselectOne',
			method:'put',
			data:data,
			success:success,
			error:error			
		})		
	},
	//购物车全选
	selectAll:function(success,error){
		_util.request({
			url:'/cart/selectAll',
			method:'put',
			success:success,
			error:error			
		})			
	},
	//购物车全不选
	unselectAll:function(success,error){
		_util.request({
			url:'/cart/unselectAll',
			method:'put',
			success:success,
			error:error			
		})			
	},
	//删除一条
	deleteOne:function(data,success,error){
		_util.request({
			url:'/cart/deleteOne',
			method:'put',
			data:data,
			success:success,
			error:error			
		})		
	},
	deleteSelected:function(success,error){
		_util.request({
			url:'/cart/deleteSelected',
			method:'put',
			success:success,
			error:error			
		})			
	},
	updateCount:function(data,success,error){
		_util.request({
			url:'/cart/updateCount',
			method:'put',
			data:data,
			success:success,
			error:error			
		})		
	}
}

module.exports = _cart;